# Generated by Django 4.1.5 on 2023-03-21 10:11

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='fileUrl',
            field=models.FileField(default='images/documents/', upload_to=documents.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
