# Generated by Django 4.1.5 on 2023-05-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_processed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_FileManager',
        ),
    ]
