# Generated by Django 4.1.5 on 2023-05-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article_Blog',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Blog',
        ),
    ]
