# Generated by Django 4.1.5 on 2023-06-23 08:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_article_article_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/blog/')),
                ('intro', ckeditor.fields.RichTextField(null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('publication_time', models.DateTimeField()),
                ('language', models.CharField(choices=[('fr', 'French'), ('nl', 'Nederlands')], default='fr', max_length=2, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('language', models.CharField(choices=[('fr', 'French'), ('nl', 'Nederlands')], default='fr', max_length=2, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='Article_Blog',
        ),
        migrations.DeleteModel(
            name='Category_Blog',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoryblog'),
        ),
    ]
