# Generated by Django 4.1.5 on 2023-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rootcategoryblog_categoryblog_root_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcategoryblog',
            name='translations',
            field=models.ManyToManyField(blank=True, to='blog.categoryblog', verbose_name='Translations'),
        ),
    ]
