# Generated by Django 4.1.5 on 2023-06-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rootcategoryblog_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootcategoryblog',
            name='translations',
        ),
    ]
