# Generated by Django 4.1.5 on 2023-06-23 09:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_rootcategoryblog_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/blog/')),
                ('intro', ckeditor.fields.RichTextField(null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('publication_time', models.DateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoryblog')),
            ],
            options={
                'verbose_name': 'Root article',
                'verbose_name_plural': 'Root articles',
            },
        ),
        migrations.AddField(
            model_name='articleblog',
            name='root_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.rootarticleblog', verbose_name='Root article'),
        ),
    ]
