# Generated by Django 4.1.5 on 2023-06-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rootarticleblog_articleblog_root_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootarticleblog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.rootcategoryblog'),
        ),
    ]
