# Generated by Django 4.1.5 on 2023-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articleblog_slug_rootarticleblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootarticleblog',
            name='with_translations',
            field=models.BooleanField(default=True, verbose_name='With translations'),
        ),
    ]
