# Generated by Django 4.1.5 on 2023-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rootarticleblog_with_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootarticleblog',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('nl', 'Nederlands')], default='fr', max_length=2, null=True, verbose_name='Language'),
        ),
    ]
