# Generated by Django 4.1.5 on 2023-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rootarticleblog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootarticleblog',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('nl', 'Nederlands')], default='fr', max_length=2, null=True, verbose_name='Language'),
        ),
    ]
