version: '2'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    hostname: loki-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  loki:
    image: percil/silva_loki
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8001:8001"
