# Generated by Django 4.1.5 on 2023-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silvauser',
            name='mobile',
        ),
    ]
