# Generated by Django 4.1.5 on 2023-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'yearly')], default=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
