# Generated by Django 4.1.5 on 2023-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_event_recurrency_alter_event_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='Debut',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='Fin',
            field=models.DateTimeField(null=True),
        ),
    ]
