# Generated by Django 4.1.5 on 2023-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_rename_start_datetime_event_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rrule',
            new_name='rrule_start',
        ),
        migrations.AddField(
            model_name='event',
            name='rrule_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Debut',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Fin',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
