# Generated by Django 4.1.5 on 2023-02-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0004_rename_rrule_event_rrule_start_event_rrule_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rrule_start',
            new_name='rrule',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rrule_end',
        ),
    ]
