# Generated by Django 4.1.5 on 2023-03-03 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0005_rename_rrule_start_event_rrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
